const express = require('express');
const {register, login, followUser, logout, updatePassword} = require('../controllers/user');
const {isAuthenticated} = require('../middlewares/auth');
const router = express.Router();
router.route("/register").post(register);
router.route("/login").post(login);
router.route("/follow/:id").get(isAuthenticated,followUser);
router.route("/logout").get(isAuthenticated,logout);
router.route("/update/password").put(isAuthenticated,updatePassword);
module.exports = router;